platform :ios, '8.0'

source 'https://gitcafe.com/akuandev/Specs.git'

pod 'AFNetworking', '~> 2.6.0'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'FMDB', '~> 2.5.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Mantle', '~> 2.0.2'
pod 'pop', '~> 1.0.8'
pod 'Reachability', '~> 3.2.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'Shimmer', '~> 1.0.2'
pod 'SSKeychain', '~> 1.2.3'
pod 'UIView+Shake', '~> 1.1.0'